// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type GoogleToken struct {
	Token string `json:"token"`
}

type Mutation struct {
}

type Profile struct {
	ProfileType string  `json:"profileType"`
	EntityRef   string  `json:"entityRef"`
	Network     string  `json:"network"`
	Action      *string `json:"action,omitempty"`
}

type ProfileMetrics struct {
	ContractAddress           *string  `json:"contractAddress,omitempty"`
	ContractName              *string  `json:"contractName,omitempty"`
	LogoURL                   *string  `json:"logoURL,omitempty"`
	TotalBalance              *float64 `json:"totalBalance,omitempty"`
	BalanceVolatility         *float64 `json:"balanceVolatility,omitempty"`
	DownsideVolatility        *float64 `json:"downsideVolatility,omitempty"`
	MaxDrawdown               *float64 `json:"maxDrawdown,omitempty"`
	DrawDownVolatility        *float64 `json:"drawDownVolatility,omitempty"`
	GiniCoefficientOfBalances *float64 `json:"giniCoefficientOfBalances,omitempty"`
}

type ProfileResponse struct {
	ProfileType string            `json:"profileType"`
	EntityRef   string            `json:"entityRef"`
	Network     string            `json:"network"`
	Metrics     []*ProfileMetrics `json:"metrics,omitempty"`
}

type Query struct {
}

type RefreshTokenInput struct {
	Token string `json:"token"`
}

type User struct {
	Username string `json:"username"`
	Password string `json:"password"`
}
