package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"fmt"
	"log/slog"

	"github.com/Zayn-Rekhi/cryptorisk/graph/model"
	"github.com/Zayn-Rekhi/cryptorisk/internal/auth"
	"github.com/Zayn-Rekhi/cryptorisk/internal/metrics"
	"github.com/Zayn-Rekhi/cryptorisk/internal/profile"
	"github.com/Zayn-Rekhi/cryptorisk/internal/users"
	"github.com/Zayn-Rekhi/cryptorisk/pckg/jwt"
)

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input model.User) (string, error) {
	var user users.User
	user.Username = input.Username
	user.Password = input.Password

	user.CreateUser()

	token, err := jwt.GenerateToken(user.Username)
	if err != nil {
		slog.Error("Error Level: ", "description", "CreateUser()", "error", err.Error())
		return "", err
	}

	slog.Info("Info Level: ", "description", "CreateUser()", "User", fmt.Sprintf("%+v", user), "jwt", token)

	return token, nil
}

// UpdateUserProfile is the resolver for the updateUserProfile field.
func (r *mutationResolver) UpdateUserProfile(ctx context.Context, input model.Profile) (string, error) {
	user := auth.ForContext(ctx)
	if user == nil {
		slog.Error("Error Level: ", "description", "UpdateUserProfile()", "error", "Access Denied")
		return "", fmt.Errorf("access denied")
	}

	var prof profile.Profile
	prof.ProfileType = input.ProfileType
	prof.EntityRef = input.EntityRef
	prof.Network = input.Network
	prof.ConstructProfile()

	slog.Info("Info Level: ", "description", "UpdateUserProfile()", "User", fmt.Sprintf("%+v", user), "Profile", fmt.Sprintf("%+v", prof))

	switch *input.Action {
	case "add":
		users.AddProfileForUserByUsername(*user, prof.ID)
		return user.ID.String(), nil
	case "remove":
		users.RemoveProfileForUserByUsername(*user, prof.ID)
		return user.ID.String(), nil
	}

	return "", fmt.Errorf("Not a valid operation!")
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input model.User) (string, error) {
	var user users.User

	user.Username = input.Username
	user.Password = input.Password

	correct := user.Authenticate()

	if !correct {
		slog.Error("Error Level: ", "description", "Login()", "error", "Access Denied: Wrong Username or Password")
		return "", &users.WrongUsernameOrPasswordError{}
	}

	token, err := jwt.GenerateToken(user.Username)
	if err != nil {
		slog.Error("Error Level: ", "description", "Login()", "error", "Cannot generate token")
		return "", err
	}

	slog.Info("Info Level: ", "description", "Login()", "User", fmt.Sprintf("%+v", user))
	return token, nil
}

// LoginGoogle is the resolver for the loginGoogle field.
func (r *mutationResolver) LoginGoogle(ctx context.Context, input model.GoogleToken) (string, error) {
	var user users.User

	user.InitializeGoogleUser(input.Token)

	token, err := jwt.GenerateToken(user.Username)
	if err != nil {
		slog.Error("Error Level: ", "description", "LoginGoogle()", "error", "Cannot generate token")
		return "", err
	}

	slog.Info("Info Level: ", "description", "LoginGoogle()", "User", fmt.Sprintf("%+v", user))
	return token, nil
}

// RefreshToken is the resolver for the refreshToken field.
func (r *mutationResolver) RefreshToken(ctx context.Context, input model.RefreshTokenInput) (string, error) {
	username, err := jwt.ParseToken(input.Token)
	if err != nil {
		slog.Error("Error Level: ", "description", "RefreshToken()", "error", "Access Denied")
		return "", fmt.Errorf("access denied")
	}
	token, err := jwt.GenerateToken(username)
	if err != nil {
		slog.Error("Error Level: ", "description", "RefreshToken()", "error", err.Error())
		return "", err
	}

	slog.Info("Info Level: ", "description", "RefreshToken()")
	return token, nil
}

// Metrics is the resolver for the metrics field.
func (r *queryResolver) Metrics(ctx context.Context, profile []*model.Profile, window int32) ([]*model.ProfileResponse, error) {
	user := auth.ForContext(ctx)
	if user == nil {
		slog.Error("Error Level: ", "description", "Metrics Query", "error", "Access Denied")
		return nil, fmt.Errorf("access denied")
	}

	profile_metrics, err := metrics.ComputeBalanceMetrics(profile, window)
	if err != nil {
		slog.Error("Error Level: ", "description", "Metrics Query", "error", err.Error())
		return nil, fmt.Errorf("error with computing metrics")
	}

	slog.Info("Info Level: ", "description", "Metrics Query", "User", fmt.Sprintf("%+v", user))
	return profile_metrics, nil
}

// Profiles is the resolver for the profiles field.
func (r *queryResolver) Profiles(ctx context.Context) ([]*model.ProfileResponse, error) {
	user := auth.ForContext(ctx)

	if user == nil {
		slog.Error("Error Level: ", "description", "Profiles Query", "error", "Access Denied")
		return nil, fmt.Errorf("access denied")
	}

	profs, err := profile.GetProfilesByReferences((*user).ProfileReferences)

	if err != nil {
		slog.Error("Error Level: ", "description", "Profiles Query", "error", err.Error())
		return nil, err
	}

	prof_resp, err := profile.ToProfiles(profs)

	if err != nil {
		slog.Error("Error Level: ", "description", "Profiles Query", "error", err.Error())
		return nil, err
	}

	slog.Info("Info Level: ", "description", "Profiles Query", "User", fmt.Sprintf("%+v", user))
	return prof_resp, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
